//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ferrari_Browser.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ferrari_Browser.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ferrari Browser is an app which allows you to check out all the differant types of Ferrari&apos;s. A browser is included which allows you to visit and browse around the offical Ferrari website. This app is stickly a fan app. Resources, ie images and information where used from: wikepedia.com, ferrari.com and googleimages. This app is not intended for profit making purposes. .
        /// </summary>
        public static string AboutBrowser {
            get {
                return ResourceManager.GetString("AboutBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This browser is not designed to go to any site but the ferrari website. This app was designed as a fan app, some of the information you see in this app was taken from Ferrari.com so for more information visit there..
        /// </summary>
        public static string AboutTheBrowser {
            get {
                return ResourceManager.GetString("AboutTheBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ferrari Browser.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ferrari 125 S was the first vehicle produced and built by automaker Ferrari. It debuted on May 11, 1947 at the Piacenza racing circuit. It was a racing sports car and featured a V12 engine a trait it shared with most Ferrari cars of the following decades. This engine produced 118 bhp.
        ///The 125 S debuted at the Circuito di Piacenza, driven by Franco Cortese, but  was unable to finish the race despite a strong showing. Fourteen days later, the 125 S claimed Ferrari&apos;s first victory at the Grand Prix of Rom [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ferrari125s {
            get {
                return ResourceManager.GetString("ferrari125s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed for long distance competition, the 166 MM took its name from one of the world’s most famous road races, the Mille Miglia.
        ///The 166 MM was both extremely light and extremely dynamic whilst still maintaining significant structural stiffness.
        ///The 166 MM’s engine was also modified for run on “normal” commercially available fuel.
        /// </summary>
        public static string ferrari166mm {
            get {
                return ResourceManager.GetString("ferrari166mm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ferrari 250 GT Lusso is a GT car which was manufactured by Italian automaker Ferrari from 1963 to 1964.
        /// Keeping in line with the Ferrari tradition of that time, the 250 GT Lusso was designed by the Turinese coachbuilder Pininfarina, and bodied by Carrozzeria Scaglietti. Regarded by many as one of the most beautiful Ferraris ever made.
        /// </summary>
        public static string ferrari250GT {
            get {
                return ResourceManager.GetString("ferrari250GT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ferrari TR, or 250 Testa Rossa, is a race car model built by Ferrari in the 1950s and 60s.
        ///These cars dominated their competitors, with variations winning the 24 Hours of Le Mans in 1958, 1960, and 1961.
        ///In all, thirty-four 250 Testa Rossas were built, from 1956 through 1961.
        ///Testa Rossa is the second most valuable Ferrari model, often valued at more than US$8,000,000.&quot;.
        /// </summary>
        public static string ferrari250TestaRossa {
            get {
                return ResourceManager.GetString("ferrari250TestaRossa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ferrari America is a series of top-end Ferrari models built in the 1950s and 1960s. They were large touring cars with the largest V12 engines and often had custom bodywork.
        ///All America models used a live axle in the rear, were front-engined, and had worm and sector steering.
        /// </summary>
        public static string ferrari375America {
            get {
                return ResourceManager.GetString("ferrari375America", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ferrari 458 is a mid-engined sports car produced by the Italian sports car manufacturer Ferrari. The 458 replaced the Ferrari F430, and was first officially unveiled at the 2009 Frankfurt Motor Show.
        ///The 458 is powered by a 4.5 L (270 cu in) V8 engine derived from a shared Ferrari/Maserati design, producing 570 PS (419 kW; 562 hp).
        /// </summary>
        public static string ferrari458Challenge {
            get {
                return ResourceManager.GetString("ferrari458Challenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ferrari 458 is a mid-engined sports car produced by the Italian sports car manufacturer Ferrari.
        ///The 458 replaced the Ferrari F430, and was first officially unveiled at the 2009 Frankfurt Motor Show. The 458 is powered by a 4.5 L (270 cu in) V8 engine derived from a shared Ferrari/Maserati design, producing 570 PS (419 kW; 562 hp)&quot;.
        /// </summary>
        public static string ferrari458Italia {
            get {
                return ResourceManager.GetString("ferrari458Italia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ferrari California is a grand touring sports car produced by the Italian manufacturer Ferrari.
        ///It is a two door &apos;2+2&apos; hard top convertible. When originally released, the California was powered by a front-mid mounted gasoline direct injection 4.3 L (260 cu in) V8 with 460 PS (338 kW; 454 hp)..
        /// </summary>
        public static string ferrariCalifornia {
            get {
                return ResourceManager.GetString("ferrariCalifornia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Enzo Ferrari is a 12 cylinder mid-engine berlinetta supercar named after the company&apos;s founder, Enzo Ferrari.
        ///It was built in 2002 using Formula One technology such as a carbon-fibre body, F1-style electrohydraulic shift transmission.  Also used are technologies not allowed in F1 such as active aerodynamics and traction control.
        ///The Enzo&apos;s V12 engine is the first of a new generation for Ferrari. It is based on the design of the V8  found in Maserati&apos;s Quattroporte. The Enzo can accelerate to 60 mph (9 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ferrariEnzo {
            get {
                return ResourceManager.GetString("ferrariEnzo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ferrari F12 berlinetta (also unofficially referred to as the F12 Berlinetta or the F12) is a front mid-engine rear-wheel-drive grand tourer produced by Italian sports car manufacturer Ferrari.
        ///The F12berlinetta, introduced to the public at the 2012 Geneva Motor Show, replaces the 599 series grand tourers.
        ///The naturally aspirated 6.3 litre Ferrari V12 engine in the F12berlinetta has won the International Engine of the Year Awards 2013 in the Best Performance category and Best Engine above 4.0 litres. T [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ferrariF12Berlinetta {
            get {
                return ResourceManager.GetString("ferrariF12Berlinetta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ferrari F40 is a mid-engine, rear-wheel drive, two-door coupé sports car built from 1987 to 1992.
        ///It was designed to celebrate Ferrari&apos;s 40th anniversary and was the last Ferrari automobile personally approved by Enzo Ferrari..
        /// </summary>
        public static string ferrariF40 {
            get {
                return ResourceManager.GetString("ferrariF40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ferrari F50 is a mid-engined range-topping sports car made by Ferrari. The F50 was introduced in 1995. The car is a two door, two seat roadster with a removable hardtop.
        ///It has a 4.7 L naturally aspirated 60-valve V12 engine that was developed from the 3.5 L V12 used in the 1990 Ferrari 641 Formula One car.
        /// </summary>
        public static string ferrariF50 {
            get {
                return ResourceManager.GetString("ferrariF50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ferrari FF (FF meaning &apos;Ferrari Four&apos;, for four seats and four-wheel drive) is a grand tourer presented by Ferrari on March 1, 2011 at the Geneva Motor Show.  It is Ferrari&apos;s first production four-wheel drive model. It replaced the 612 Scaglietti grand tourer. The FF has a top speed of 335 km/h (208 mph), and it accelerates from zero to 100 km/h (62 mph) in 3.7 seconds. The FF costs US$300,000.
        /// </summary>
        public static string ferrariFF {
            get {
                return ResourceManager.GetString("ferrariFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ferrari 250 GTO is a racing GT car which was produced by Ferrari from 1962 to 1964.
        ///The 250 GTO was designed to compete in GT racing. The engine was the Tipo 168/62 Comp. 3.0 L V12 as used in the 250 Testa Rossa..
        /// </summary>
        public static string ferrariGTO {
            get {
                return ResourceManager.GetString("ferrariGTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LaFerrari (also known by its project name, F150) is a limited production hybrid supercar built by Ferrari.
        ///The car and its name were officially unveiled at the 2013 Geneva Auto Show. LaFerrari is the first mild hybrid from Ferrari, providing the highest power output of any Ferrari whilst decreasing fuel consumption by 40 percent. LaFerrari&apos;s mid rear mounted 65° V12 Internal Combustion Engine has a 6.3 litre (6262 cc) capacity producing 800 PS (588 kW, 789 bhp).
        /// </summary>
        public static string ferrariLaFerrari {
            get {
                return ResourceManager.GetString("ferrariLaFerrari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ferrari is an Italian luxury sports car manufacturer based in Maranello. 
        ///Founded by Enzo Ferrari in 1929, the company manufactured race cars before moving into production of street-legal vehicles in 1947.
        ///    The first Ferrari road car was the 1947 125 S, powered by a 1.5L V12 engine. Early in 1969, Fiat took a 50% stake in Ferrari and in 2008 they expanded that stake to 85%. 
        ///    In 1988, Enzo Ferrari oversaw the launch of the Ferrari F40, the last new Ferrari to be launched before his death later that [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FerrarisHistory {
            get {
                return ResourceManager.GetString("FerrarisHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Runtime Property Value.
        /// </summary>
        public static string SampleProperty {
            get {
                return ResourceManager.GetString("SampleProperty", resourceCulture);
            }
        }
    }
}
